GET http://localhost:8080/api/logs

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "username": "Titus",
    "password": "fleshbad"
}

###

POST http://localhost:8080/auth/logout
